kind = "web"
previewPath = "/"
title = "Miniondle"
version = "1.0.0"
id = "artifacts/miniondle"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20920

[services.development]
run = "pnpm --filter @workspace/miniondle run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/miniondle", "run", "build" ]
publicDir = "artifacts/miniondle/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20920"
BASE_PATH = "/"
